[package]
name = "stac2"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = "0.2"
rand = { version = "0.10", features = ["serde", "chacha"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1"
tsi = { path = "../tsi" }
