set_property PACKAGE_PIN {E3} [get_ports {io_clock}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_clock}]
set_property PACKAGE_PIN {A9} [get_ports {uart_rxd}]
set_property IOSTANDARD {LVCMOS33} [get_ports {uart_rxd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart_rxd}]]]
set_property PACKAGE_PIN {D10} [get_ports {uart_txd}]
set_property IOSTANDARD {LVCMOS33} [get_ports {uart_txd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart_txd}]]]
set_property PACKAGE_PIN {G6} [get_ports {led_0}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_0}]
set_property PACKAGE_PIN {F6} [get_ports {led_1}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_1}]
set_property PACKAGE_PIN {E1} [get_ports {led_2}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_2}]
set_property PACKAGE_PIN {G3} [get_ports {led_3}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_3}]
set_property PACKAGE_PIN {J4} [get_ports {led_4}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_4}]
set_property PACKAGE_PIN {G4} [get_ports {led_5}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_5}]
set_property PACKAGE_PIN {J3} [get_ports {led_6}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_6}]
set_property PACKAGE_PIN {J2} [get_ports {led_7}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_7}]
set_property BOARD_PIN {reset} [get_ports {io_reset}]
set_property PACKAGE_PIN {D9} [get_ports {reset_btn}]
set_property IOSTANDARD {LVCMOS33} [get_ports {reset_btn}]
set_property PACKAGE_PIN {G13} [get_ports {serial_tl_clock_in}]
set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_clock_in}]
set_property PACKAGE_PIN {B11} [get_ports {serial_tl_out_valid}]
set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_out_valid}]
set_property PACKAGE_PIN {A11} [get_ports {serial_tl_out_ready}]
set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_out_ready}]
set_property PACKAGE_PIN {D12} [get_ports {serial_tl_out_bits}]
set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_out_bits}]
set_property PACKAGE_PIN {B18} [get_ports {serial_tl_in_valid}]
set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_in_valid}]
set_property PACKAGE_PIN {A18} [get_ports {serial_tl_in_ready}]
set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_in_ready}]
set_property PACKAGE_PIN {K16} [get_ports {serial_tl_in_bits}]
set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_in_bits}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {serial_tl_out_valid}]]]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanout -flat -endpoints_only [get_ports {serial_tl_out_ready}]]]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {serial_tl_out_bits}]]]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanout -flat -endpoints_only [get_ports {serial_tl_in_valid}]]]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {serial_tl_in_ready}]]]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanout -flat -endpoints_only [get_ports {serial_tl_in_bits}]]]
set_property CLOCK_DEDICATED_ROUTE {FALSE} [get_nets [get_ports {serial_tl_clock_in}]]
set_property PACKAGE_PIN {D13} [get_ports {io_ctl_clk}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_clk}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -endpoints_only [get_ports {io_ctl_clk}]]]
set_property CLOCK_DEDICATED_ROUTE {FALSE} [get_nets [get_ports {io_ctl_clk}]]
set_property SLEW FAST [get_ports io_ctl_clk]
set_property DRIVE 16 [get_ports io_ctl_clk]
set_property PACKAGE_PIN {V15} [get_ports {io_ctl_reset}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_reset}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_reset}]]]
set_property PACKAGE_PIN {U12} [get_ports {io_ctl_sramScanMode}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_sramScanMode}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_sramScanMode}]]]
set_property PACKAGE_PIN {V12} [get_ports {io_ctl_pllArstb}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_pllArstb}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_pllArstb}]]]
set_property PACKAGE_PIN {V10} [get_ports {io_ctl_pllScanClk}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_pllScanClk}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_pllScanClk}]]]
set_property PACKAGE_PIN {V11} [get_ports {io_ctl_pllScanEn}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_pllScanEn}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_pllScanEn}]]]
set_property PACKAGE_PIN {U14} [get_ports {io_ctl_pllScanIn}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_pllScanIn}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_pllScanIn}]]]
set_property PACKAGE_PIN {V14} [get_ports {io_ctl_pllScanOut}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_pllScanOut}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanout -flat -endpoints_only [get_ports {io_ctl_pllScanOut}]]]
set_property PACKAGE_PIN {T13} [get_ports {io_ctl_pllScanRstn}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_pllScanRstn}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_pllScanRstn}]]]
set_property PACKAGE_PIN {U13} [get_ports {io_ctl_pllSel}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_pllSel}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_pllSel}]]]
set_property PACKAGE_PIN {D4} [get_ports {io_ctl_sramBistStart}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_sramBistStart}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_sramBistStart}]]]
set_property PACKAGE_PIN {D3} [get_ports {io_ctl_sramEn}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_sramEn}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_sramEn}]]]
set_property PACKAGE_PIN {F4} [get_ports {io_ctl_sramBistEn}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_sramBistEn}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_sramBistEn}]]]
set_property PACKAGE_PIN {F3} [get_ports {io_ctl_sramExtEn}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_sramExtEn}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_sramExtEn}]]]
set_property PACKAGE_PIN {E2} [get_ports {io_ctl_sramScanIn}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_sramScanIn}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_sramScanIn}]]]
set_property PACKAGE_PIN {D2} [get_ports {io_ctl_sramScanOut}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_sramScanOut}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanout -flat -endpoints_only [get_ports {io_ctl_sramScanOut}]]]
set_property PACKAGE_PIN {H2} [get_ports {io_ctl_sramScanEn}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_sramScanEn}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {io_ctl_sramScanEn}]]]
set_property PACKAGE_PIN {G2} [get_ports {io_ctl_sramBistDone}]
set_property IOSTANDARD {LVCMOS33} [get_ports {io_ctl_sramBistDone}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanout -flat -endpoints_only [get_ports {io_ctl_sramBistDone}]]]
